/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.lista5;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus Moreira Fonseca RA:1426885
 */
public class ConsultaPasseio extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPasseio
     */
    public ConsultaPasseio() {
        initComponents();

    }

    private void listarVeiculosPasseio() {
        DefaultTableModel tabModel = (DefaultTableModel) TbVeiculos.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);

        // Assuming you have a collection of VeiculoPasseio objects
        for (Veiculo v : BancoVeic.getBanco().getBdVeiculosPasseio()) {
            tabModel.insertRow(posLin, new Object[]{
                v.getPlaca(),
                v.getMarca(),
                v.getModelo(),
                v.getCor(),
                v.getQtdRodas(),
                v.getVelocMax(),
                v.getQtdPistoes(),
                v.getPotencia(),
                v.getDataCadastro(),
                v.getQtdPassageiro()
            });
            posLin++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleVeiculos = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VeiculosPasseio = new javax.swing.JScrollPane();
        TbVeiculos = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TitleVeiculos.setText("Veiculos de Passeio");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        TbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor", "QtdRodas", "VelocMax", "QtdPistoes", "Potencia", "DataCadastro", "QtdPassageiro"
            }
        ));
        VeiculosPasseio.setViewportView(TbVeiculos);

        jScrollPane1.setViewportView(VeiculosPasseio);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Sair))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addGap(852, 852, 852))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleVeiculos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(TitleVeiculos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(Sair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
        Principal principal = Principal.getInstance();
        principal.setVisible(true);
    }//GEN-LAST:event_SairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarVeiculosPasseio();
    }//GEN-LAST:event_formWindowActivated

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        int selectedRowIndex = TbVeiculos.getSelectedRow();
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String placa = TbVeiculos.getValueAt(selectedRowIndex, 0).toString();

        excluirVeiculo(placa);


    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        int selectedRowIndex = TbVeiculos.getSelectedRow();
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String placa = TbVeiculos.getValueAt(selectedRowIndex, 0).toString();
        Veiculo veiculo = BancoVeic.getVeiculoByPlaca(placa);

        // Obtenha os outros dados do veículo do banco de dados
        String marca = veiculo.getMarca();
        String modelo = veiculo.getModelo();
        String cor = veiculo.getCor();
        int qtdRodas = veiculo.getQtdRodas();
        int velocMax = veiculo.getVelocMax();
        int qtdPistoes = veiculo.getQtdPistoes();
        int potencia = veiculo.getPotencia();
        String dataCadastro = veiculo.getDataCadastro();
        int qtdePassageiro = veiculo.getQtdPassageiro();

        
        EditarPasseio editarPasseio = new EditarPasseio(placa, marca, modelo, cor, qtdRodas, velocMax, qtdPistoes, potencia, dataCadastro, qtdePassageiro);
        editarPasseio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAlterarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JTable TbVeiculos;
    private javax.swing.JLabel TitleVeiculos;
    private javax.swing.JScrollPane VeiculosPasseio;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void excluirVeiculo(String placa) {
        BancoVeic.getBanco().excluirVeiculo(placa);
        listarVeiculosPasseio();
    }

   
}
