/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.lista5;

import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class EditarPasseio extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public EditarPasseio(String placa, String marca, String modelo, String cor, int qtdRodas, int velocMax, int qtdPistoes, int potencia, String dataCadastro, int qtdePassageiro) {
        initComponents();

        // Carregar os dados do veículo nos campos correspondentes
        cxPlaca.setText(placa);
        cxPlaca.setEnabled(false);
        cxMarca.setText(marca);
        cxModelo.setText(modelo);
        cxCor.setText(cor);
        cxRodas.setText(String.valueOf(qtdRodas));
        cxVelocidade.setText(String.valueOf(velocMax));
        cxPistoes.setText(String.valueOf(qtdPistoes));
        cxPotencia.setText(String.valueOf(potencia));
        cxData.setText(dataCadastro);
        cxPassageiros.setText(String.valueOf(qtdePassageiro));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxPlaca = new javax.swing.JTextField();
        rotPlaca = new javax.swing.JLabel();
        cxModelo = new javax.swing.JTextField();
        rotModelo = new javax.swing.JLabel();
        cxMarca = new javax.swing.JTextField();
        rotMarca = new javax.swing.JLabel();
        cxCor = new javax.swing.JTextField();
        rotCor = new javax.swing.JLabel();
        cxPotencia = new javax.swing.JTextField();
        rotData = new javax.swing.JLabel();
        cxVelocidade = new javax.swing.JTextField();
        rotVelocidade = new javax.swing.JLabel();
        cxPistoes = new javax.swing.JTextField();
        rotPistoes = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();
        rotPotencia = new javax.swing.JLabel();
        cxRodas = new javax.swing.JTextField();
        rotRodas = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        bSalvarContinuar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        rotNome = new javax.swing.JLabel();
        cxPassageiros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotPlaca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotPlaca.setText("Placa");

        rotModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotModelo.setText("Modelo");

        rotMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotMarca.setText("Marca");

        rotCor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotCor.setText("Cor");

        rotData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotData.setText("Data Cadastro");

        rotVelocidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotVelocidade.setText("Velocidade Max");

        rotPistoes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotPistoes.setText("Qtd Pistoes");

        rotPotencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotPotencia.setText("Potencia Motor");

        rotRodas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotRodas.setText("Qtd Rodas");

        bLimpar.setText("Limpar");
        bLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLimparMouseClicked(evt);
            }
        });

        bSalvarContinuar.setText("Salvar e Voltar");
        bSalvarContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarContinuarMouseClicked(evt);
            }
        });
        bSalvarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarContinuarActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        rotNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNome.setText("Numero de passageiros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotCor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(Sair))
                    .addComponent(cxPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalvarContinuar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sair)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotPotencia)
                            .addComponent(rotPlaca))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotMarca)
                    .addComponent(rotVelocidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotModelo)
                    .addComponent(rotPistoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCor)
                    .addComponent(rotData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotRodas)
                    .addComponent(rotNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvarContinuar)
                    .addComponent(bLimpar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalvarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarContinuarActionPerformed

        String placa = cxPlaca.getText();

        String marca = cxMarca.getText();
        String modelo = cxModelo.getText();
        String cor = cxCor.getText();
        int qtdRodas = Integer.parseInt(cxRodas.getText());
        int velocMax = Integer.parseInt(cxVelocidade.getText());
        int qtdPistoes = Integer.parseInt(cxPistoes.getText());
        int potencia = Integer.parseInt(cxPotencia.getText());
        String dataCadastro = cxData.getText();
        int qtdePassageiro = Integer.parseInt(cxPassageiros.getText());

        BancoVeic banco = BancoVeic.getBanco();
        Veiculo veiculo = banco.getVeiculoByPlaca(placa); // Obtenha o veículo com a placa correspondente

        if (veiculo != null) {
            // Atualize os atributos do veículo existente
            veiculo.setMarca(marca);
            veiculo.setModelo(modelo);
            veiculo.setCor(cor);
            veiculo.setQtdRodas(qtdRodas);
            veiculo.setVelocMax(velocMax);
            veiculo.setQtdPistoes(qtdPistoes);
            veiculo.setPotencia(potencia);
            veiculo.setDataCadastro(dataCadastro);
            veiculo.setQtdPassageiro(qtdePassageiro);

            ConsultaPasseio consultaPasseio = new ConsultaPasseio();
            consultaPasseio.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Veículo não encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSalvarContinuarActionPerformed

    private void bSalvarContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarContinuarMouseClicked


    }//GEN-LAST:event_bSalvarContinuarMouseClicked

    private void bLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseClicked
        limpar();
    }//GEN-LAST:event_bLimparMouseClicked

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
        Principal principal = Principal.getInstance();
        principal.setVisible(true);
    }//GEN-LAST:event_SairActionPerformed

    public void limpar() {
        
        cxModelo.setText("");
        cxMarca.setText("");
        cxCor.setText("");
        cxRodas.setText("");
        cxVelocidade.setText("");
        cxPistoes.setText("");
        cxPotencia.setText("");
        cxData.setText("");
        cxPassageiros.setText("");
        cxPlaca.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSalvarContinuar;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxData;
    private javax.swing.JTextField cxMarca;
    private javax.swing.JTextField cxModelo;
    private javax.swing.JTextField cxPassageiros;
    private javax.swing.JTextField cxPistoes;
    private javax.swing.JTextField cxPlaca;
    private javax.swing.JTextField cxPotencia;
    private javax.swing.JTextField cxRodas;
    private javax.swing.JTextField cxVelocidade;
    private javax.swing.JLabel rotCor;
    private javax.swing.JLabel rotData;
    private javax.swing.JLabel rotMarca;
    private javax.swing.JLabel rotModelo;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotPistoes;
    private javax.swing.JLabel rotPlaca;
    private javax.swing.JLabel rotPotencia;
    private javax.swing.JLabel rotRodas;
    private javax.swing.JLabel rotVelocidade;
    // End of variables declaration//GEN-END:variables

}
