/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.lista5;


 /**
 *
 * @author Mateus Moreira Fonseca RA:1426885
 */
public class Principal extends javax.swing.JFrame {

    private static Principal instance;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    public static Principal getInstance() {
        if (instance == null) {
            instance = new Principal();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        PasseioItem = new javax.swing.JMenuItem();
        CargaItem = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenu();
        PasseioItemConsulta = new javax.swing.JMenuItem();
        CargaItemConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cadastro.setText("Cadastrar");

        PasseioItem.setText("Cadastrar Veiculo de Passeio");
        PasseioItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasseioItemMouseClicked(evt);
            }
        });
        PasseioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasseioItemActionPerformed(evt);
            }
        });
        Cadastro.add(PasseioItem);

        CargaItem.setText("Casdastrar Veiculo de Carga");
        CargaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargaItemMouseClicked(evt);
            }
        });
        CargaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaItemActionPerformed(evt);
            }
        });
        Cadastro.add(CargaItem);

        MenuPrincipal.add(Cadastro);

        Consulta.setText("Consulta");

        PasseioItemConsulta.setText("Consulta Veiculo de Passeio");
        PasseioItemConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasseioItemConsultaMouseClicked(evt);
            }
        });
        PasseioItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasseioItemConsultaActionPerformed(evt);
            }
        });
        Consulta.add(PasseioItemConsulta);

        CargaItemConsulta.setText("Consulta Veiculo de Carga");
        CargaItemConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargaItemConsultaMouseClicked(evt);
            }
        });
        CargaItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaItemConsultaActionPerformed(evt);
            }
        });
        Consulta.add(CargaItemConsulta);

        MenuPrincipal.add(Consulta);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasseioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasseioItemActionPerformed
        CadastroPasseio cadastroPasseio = new CadastroPasseio();// TODO ad  CadastroPasseio cadastroPasseio = new CadastroPasseio();
        cadastroPasseio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PasseioItemActionPerformed

    private void PasseioItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasseioItemMouseClicked


    }//GEN-LAST:event_PasseioItemMouseClicked

    private void CargaItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaItemMouseClicked

    }//GEN-LAST:event_CargaItemMouseClicked

    private void PasseioItemConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasseioItemConsultaMouseClicked

    }//GEN-LAST:event_PasseioItemConsultaMouseClicked

    private void PasseioItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasseioItemConsultaActionPerformed
        ConsultaPasseio consultaPasseio = new ConsultaPasseio();        
        consultaPasseio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PasseioItemConsultaActionPerformed

    private void CargaItemConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaItemConsultaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CargaItemConsultaMouseClicked

    private void CargaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaItemActionPerformed
        CadastroCarga cadastroCarga = new CadastroCarga();
        cadastroCarga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargaItemActionPerformed

    private void CargaItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaItemConsultaActionPerformed
        ConsultaCarga consultaCarga = new ConsultaCarga();        
        consultaCarga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargaItemConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            Principal.getInstance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem CargaItem;
    private javax.swing.JMenuItem CargaItemConsulta;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem PasseioItem;
    private javax.swing.JMenuItem PasseioItemConsulta;
    // End of variables declaration//GEN-END:variables
}
