
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mateus Moreira Fonseca RA:1426885
 */
public class EditarContaPoupanca extends javax.swing.JFrame {

    private static EditarContaPoupanca instancia;
    private JDialog confirmationDialog;

    public EditarContaPoupanca() {
        initComponents();
        rotTituloPaginaPP.requestFocus();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    public static EditarContaPoupanca getInstance() {
        if (instancia == null) {
            instancia = new EditarContaPoupanca();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNConta = new javax.swing.JLabel();
        rotNAg = new javax.swing.JLabel();
        rotTituloPaginaPP = new javax.swing.JLabel();
        rotSenha = new javax.swing.JLabel();
        rotConfirmeSenha = new javax.swing.JLabel();
        rotSaldoIncial = new javax.swing.JLabel();
        rotLimiteCP = new javax.swing.JLabel();
        cxAgencia = new javax.swing.JTextField();
        cxSaldoInicial = new javax.swing.JTextField();
        cxTaxaJuros = new javax.swing.JTextField();
        btSalvarCP = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        pwSenha = new javax.swing.JPasswordField();
        pwConfirmeSenha = new javax.swing.JPasswordField();
        Separador = new javax.swing.JSeparator();
        rotCifrao = new javax.swing.JLabel();
        rotPorcentagem = new javax.swing.JLabel();
        cxNumeroConta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotNConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNConta.setText("Numero da Conta :");

        rotNAg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNAg.setText("Numero da Agencia:");

        rotTituloPaginaPP.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        rotTituloPaginaPP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotTituloPaginaPP.setText("| Editar Conta Poupança |");

        rotSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotSenha.setText("Senha:");

        rotConfirmeSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotConfirmeSenha.setText("Confirme a Senha:");

        rotSaldoIncial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotSaldoIncial.setText("Saldo Inicial:");

        rotLimiteCP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotLimiteCP.setText("Taxa de Juros");

        cxAgencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cxAgencia.setText("0000");
        cxAgencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxAgenciaMouseClicked(evt);
            }
        });
        cxAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxAgenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxAgenciaKeyTyped(evt);
            }
        });

        cxSaldoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cxSaldoInicial.setText("0.00");
        cxSaldoInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxSaldoInicialFocusLost(evt);
            }
        });
        cxSaldoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxSaldoInicialMouseClicked(evt);
            }
        });
        cxSaldoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxSaldoInicialKeyPressed(evt);
            }
        });

        cxTaxaJuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cxTaxaJuros.setText("4.18");
        cxTaxaJuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxTaxaJurosFocusLost(evt);
            }
        });
        cxTaxaJuros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxTaxaJurosMouseClicked(evt);
            }
        });
        cxTaxaJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTaxaJurosActionPerformed(evt);
            }
        });

        btSalvarCP.setText("Salvar ");
        btSalvarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCPActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        pwSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwSenha.setText("000000");
        pwSenha.setToolTipText("");
        pwSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwSenhaMouseClicked(evt);
            }
        });
        pwSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwSenhaKeyTyped(evt);
            }
        });

        pwConfirmeSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwConfirmeSenha.setText("000000");
        pwConfirmeSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwConfirmeSenhaMouseClicked(evt);
            }
        });
        pwConfirmeSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwConfirmeSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwConfirmeSenhaKeyTyped(evt);
            }
        });

        rotCifrao.setText("R$");

        rotPorcentagem.setText("%");

        cxNumeroConta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cxNumeroConta.setText("00000-X");
        cxNumeroConta.setAutoscrolls(false);
        cxNumeroConta.setEnabled(false);
        cxNumeroConta.setFocusable(false);
        cxNumeroConta.setRequestFocusEnabled(false);
        cxNumeroConta.setVerifyInputWhenFocusTarget(false);
        cxNumeroConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxNumeroContaFocusGained(evt);
            }
        });
        cxNumeroConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaMouseClicked(evt);
            }
        });
        cxNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaActionPerformed(evt);
            }
        });
        cxNumeroConta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cxNumeroContaPropertyChange(evt);
            }
        });
        cxNumeroConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxNumeroContaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separador)
            .addComponent(rotTituloPaginaPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotNConta)
                            .addComponent(rotSenha)
                            .addComponent(rotNAg)
                            .addComponent(rotConfirmeSenha))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pwConfirmeSenha)
                                .addComponent(pwSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                            .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvarCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotCifrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotLimiteCP)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cxSaldoInicial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rotSaldoIncial, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rotPorcentagem)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotTituloPaginaPP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotNConta)
                            .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotNAg)
                            .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotSenha)
                            .addComponent(pwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotConfirmeSenha)
                            .addComponent(pwConfirmeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLimpar)
                            .addComponent(btSalvarCP)
                            .addComponent(btSair)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotSaldoIncial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotCifrao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotLimiteCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotPorcentagem))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
        Principal principal = Principal.getInstance();
        principal.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCPActionPerformed

        editarContaPoupanca();
        limpar();

    }//GEN-LAST:event_btSalvarCPActionPerformed

    private void cxTaxaJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTaxaJurosActionPerformed

    }//GEN-LAST:event_cxTaxaJurosActionPerformed

    private void cxAgenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxAgenciaMouseClicked
        limparCampo(cxAgencia);
    }//GEN-LAST:event_cxAgenciaMouseClicked

    private void pwSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwSenhaMouseClicked
        limparCampo(pwSenha);
    }//GEN-LAST:event_pwSenhaMouseClicked

    private void pwConfirmeSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwConfirmeSenhaMouseClicked
        limparCampo(pwConfirmeSenha);
    }//GEN-LAST:event_pwConfirmeSenhaMouseClicked

    private void cxSaldoInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxSaldoInicialMouseClicked
        limparCampo(cxSaldoInicial);
    }//GEN-LAST:event_cxSaldoInicialMouseClicked

    private void cxTaxaJurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxTaxaJurosMouseClicked
        limparCampo(cxTaxaJuros);
    }//GEN-LAST:event_cxTaxaJurosMouseClicked

    private void cxAgenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxAgenciaKeyPressed

    }//GEN-LAST:event_cxAgenciaKeyPressed

    private void pwSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwSenhaKeyPressed

    }//GEN-LAST:event_pwSenhaKeyPressed

    private void cxSaldoInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxSaldoInicialKeyPressed

    }//GEN-LAST:event_cxSaldoInicialKeyPressed

    private void cxSaldoInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxSaldoInicialFocusLost
        formataNumero(cxSaldoInicial);
    }//GEN-LAST:event_cxSaldoInicialFocusLost

    private void pwConfirmeSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwConfirmeSenhaKeyPressed

    }//GEN-LAST:event_pwConfirmeSenhaKeyPressed

    private void cxAgenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxAgenciaKeyTyped
        limitarTamanhoCampo(4, cxAgencia, evt);    }//GEN-LAST:event_cxAgenciaKeyTyped

    private void pwSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwSenhaKeyTyped
        limitarTamanhoCampo(6, pwSenha, evt);
    }//GEN-LAST:event_pwSenhaKeyTyped

    private void pwConfirmeSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwConfirmeSenhaKeyTyped
        limitarTamanhoCampo(6, pwConfirmeSenha, evt);
    }//GEN-LAST:event_pwConfirmeSenhaKeyTyped

    private void cxTaxaJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxTaxaJurosFocusLost
        formataNumero(cxTaxaJuros);
    }//GEN-LAST:event_cxTaxaJurosFocusLost

    private void cxNumeroContaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxNumeroContaFocusGained

    }//GEN-LAST:event_cxNumeroContaFocusGained

    private void cxNumeroContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaMouseClicked

    }//GEN-LAST:event_cxNumeroContaMouseClicked

    private void cxNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaActionPerformed

    }//GEN-LAST:event_cxNumeroContaActionPerformed

    private void cxNumeroContaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cxNumeroContaPropertyChange

    }//GEN-LAST:event_cxNumeroContaPropertyChange

    private void cxNumeroContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaKeyPressed

    }//GEN-LAST:event_cxNumeroContaKeyPressed

    private void cxNumeroContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaKeyTyped

    }//GEN-LAST:event_cxNumeroContaKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvarCP;
    private javax.swing.JTextField cxAgencia;
    private javax.swing.JTextField cxNumeroConta;
    private javax.swing.JTextField cxSaldoInicial;
    private javax.swing.JTextField cxTaxaJuros;
    private javax.swing.JPasswordField pwConfirmeSenha;
    private javax.swing.JPasswordField pwSenha;
    private javax.swing.JLabel rotCifrao;
    private javax.swing.JLabel rotConfirmeSenha;
    private javax.swing.JLabel rotLimiteCP;
    private javax.swing.JLabel rotNAg;
    private javax.swing.JLabel rotNConta;
    private javax.swing.JLabel rotPorcentagem;
    private javax.swing.JLabel rotSaldoIncial;
    private javax.swing.JLabel rotSenha;
    private javax.swing.JLabel rotTituloPaginaPP;
    // End of variables declaration//GEN-END:variables

    private void limparCampo(Component componente) {
        if (componente instanceof JTextField) {
            JTextField textField = (JTextField) componente;
            textField.setText("");
        } else if (componente instanceof JPasswordField) {
            JPasswordField passwordField = (JPasswordField) componente;
            passwordField.setText("");
        }
    }

    private void limitarTamanhoCampo(int tamanhoMaximo, JTextField campo, java.awt.event.KeyEvent evt) {
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
            if (campo.getText().length() == tamanhoMaximo) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            }
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }

    private void formataNumero(JTextField campo) {
        String texto = campo.getText();

        String semLetras = texto.replaceAll("[^\\d.,]", "");

        String resultado = semLetras.replace(",", ".");

        if (!resultado.matches("\\d+\\.\\d{2}")) {

            resultado += ".00";
        }

        campo.setText(resultado);
    }

    public void editarContaPoupanca() {
        String agencia = cxAgencia.getText();
        String numeroConta = cxNumeroConta.getText();
        String senha = new String(pwSenha.getPassword());
        String confirmacaoSenha = new String(pwConfirmeSenha.getPassword());
        double saldoInicial = Double.parseDouble(cxSaldoInicial.getText());
        double taxaJurosPadrao = Double.parseDouble(cxTaxaJuros.getText());

        try {
            if (!senha.equals(confirmacaoSenha)) {
                throw new InvalidaException("As senhas não correspondem");
            }

            if (!OperacoesBancarias.validarSenha(senha)) {
                throw new InvalidaException("A senha deve conter 6 dígitos numéricos");
            }

            if (!OperacoesBancarias.validarNumeroConta(numeroConta)) {
                throw new InvalidaException("Conta deve ter 6 dígitos numéricos");
            }

            if (!OperacoesBancarias.validarAgencia(agencia)) {
                throw new InvalidaException("Agência deve ter 4 dígitos numéricos");
            }

            if (saldoInicial < 0) {
                throw new InvalidaException("O saldo inicial deve ser maior ou igual a zero");
            }

            if (taxaJurosPadrao < 2 || taxaJurosPadrao > 8) {
                throw new InvalidaException("Taxa de juros fora do intervalo para Conta Poupanca");
            }

            if (!BancoContas.verificarContaExistente(numeroConta)) {
                throw new InvalidaException("A conta não existe");
            }

            Conta contaExistente = BancoContas.getBanco().getContaByNumero(numeroConta);

            if (!(contaExistente instanceof ContaPoupanca)) {
                throw new InvalidaException("A conta não é uma Conta Poupança");
            }

          
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja salvar as alterações na conta?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta != JOptionPane.YES_OPTION) {
                return; 
            }

            ContaPoupanca contaPoupancaNova = new ContaPoupanca(numeroConta, agencia, senha, saldoInicial, taxaJurosPadrao);

            BancoContas.getBanco().excluirConta(numeroConta);
            BancoContas.getBanco().addContaPoupanca(contaPoupancaNova);

            limpar();

            String message = "<html><b>Número da Conta:</b> " + numeroConta + "<br><b>Agência:</b> " + agencia + "<br><b>Senha:</b> " + senha + "<br><br>Conta Poupança editada com sucesso</html>";
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, message, "Sucesso ao editar conta: " + numeroConta, JOptionPane.INFORMATION_MESSAGE);
            });
        } catch (InvalidaException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro de Exceção", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void carregamentoEdicao(String numeroConta) {
        pwSenha.setEchoChar('\u0000');
        pwConfirmeSenha.setEchoChar('\u0000');
        ContaPoupanca conta = (ContaPoupanca) BancoContas.getBanco().getContaByNumero(numeroConta);

        if (conta != null) {

            String agencia = conta.getAgencia();
            String senha = conta.getSenha();
            String confirmacaoSenha = senha;
            double saldoInicial = conta.getSaldo();
            double taxaJuros = conta.getJuros();

            cxNumeroConta.setText(numeroConta);
            cxAgencia.setText(agencia);
            pwSenha.setText(senha);
            pwConfirmeSenha.setText(confirmacaoSenha);
            cxSaldoInicial.setText(String.valueOf(saldoInicial));
            cxTaxaJuros.setText(String.valueOf(taxaJuros));
        }
    }

    private void limpar() {
        String numeroConta = cxNumeroConta.getText();

        ContaPoupanca conta = (ContaPoupanca) BancoContas.getBanco().getContaByNumero(numeroConta);

        if (conta != null) {

            String agencia = conta.getAgencia();
            String senha = conta.getSenha();
            String confirmacaoSenha = senha;
            double saldoInicial = conta.getSaldo();
            double taxaJuros = conta.getJuros();

            cxNumeroConta.setText(numeroConta);
            cxAgencia.setText(agencia);
            pwSenha.setText(senha);
            pwConfirmeSenha.setText(confirmacaoSenha);
            cxSaldoInicial.setText(String.valueOf(saldoInicial));
            cxTaxaJuros.setText(String.valueOf(taxaJuros));
        }
    }

}
