
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 ** @author Mateus Moreira Fonseca RA:1426885
 */
public class Principal extends javax.swing.JFrame {

    private static Principal instancia;

    public Principal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    public static Principal getInstance() {
        if (instancia == null) {
            instancia = new Principal();
        }
        return instancia;
    }

    public void sair() {
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == 0) {
            System.exit(0);

        }
    }

    /**
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotTituloPrinc = new javax.swing.JLabel();
        pnMetodos = new javax.swing.JPanel();
        pnSaque = new javax.swing.JDesktopPane();
        txTituloSaque = new javax.swing.JLabel();
        pwSenhaSaque = new javax.swing.JPasswordField();
        txValorSaque = new javax.swing.JLabel();
        cxNumeroContaSaque = new javax.swing.JTextField();
        txNumeroContaSaque = new javax.swing.JLabel();
        cxValorSaque = new javax.swing.JTextField();
        btSacar = new javax.swing.JButton();
        txSenha = new javax.swing.JLabel();
        pnTransferencia = new javax.swing.JDesktopPane();
        txContaDestino = new javax.swing.JLabel();
        pwSenhaTransferencia = new javax.swing.JPasswordField();
        txTituloTranferencia = new javax.swing.JLabel();
        txValorTransferencia = new javax.swing.JLabel();
        cxNumeroContaOrigem = new javax.swing.JTextField();
        txContaOrigem = new javax.swing.JLabel();
        cxValorTransferencia = new javax.swing.JTextField();
        btTraferir = new javax.swing.JButton();
        txSenhaTranferencia = new javax.swing.JLabel();
        cxNumeroContaDestino = new javax.swing.JTextField();
        pnDeposito = new javax.swing.JDesktopPane();
        txValorDeposito = new javax.swing.JLabel();
        cxNumeroContaDeposito = new javax.swing.JTextField();
        txNumeroContaDeposito = new javax.swing.JLabel();
        cxValorDeposito = new javax.swing.JTextField();
        btDepositar = new javax.swing.JButton();
        txTituloDeposito = new javax.swing.JLabel();
        pnSubMetodos = new javax.swing.JPanel();
        Separador = new javax.swing.JSeparator();
        pnConsultaRendimento = new javax.swing.JDesktopPane();
        cxNumeroContaConsultarRendimento = new javax.swing.JTextField();
        txNumeroContaRendimento = new javax.swing.JLabel();
        btCalcularRendimento = new javax.swing.JButton();
        txCalculoRendimento = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        pnConsultaSaldo = new javax.swing.JDesktopPane();
        cxNumeroContaConsultarSaldo = new javax.swing.JTextField();
        txNumeroContaSaldo = new javax.swing.JLabel();
        btConsultarSaldo = new javax.swing.JButton();
        txConsultarSaldo = new javax.swing.JLabel();
        txSubTitulo = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        mCriarConta = new javax.swing.JMenu();
        iCriarContaCorrente = new javax.swing.JMenuItem();
        iCriarContaPoupanca = new javax.swing.JMenuItem();
        iCriarContaPoupancaEspeial = new javax.swing.JMenuItem();
        mBuscarConta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotTituloPrinc.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        rotTituloPrinc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotTituloPrinc.setText("SISTEMA GERENCIAL ");

        pnSaque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnSaque.setOpaque(false);

        txTituloSaque.setBackground(new java.awt.Color(255, 0, 0));
        txTituloSaque.setForeground(new java.awt.Color(255, 255, 255));
        txTituloSaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txTituloSaque.setText("Saque");

        pwSenhaSaque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwSenhaSaqueMouseClicked(evt);
            }
        });
        pwSenhaSaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwSenhaSaqueKeyTyped(evt);
            }
        });

        txValorSaque.setForeground(new java.awt.Color(255, 255, 255));
        txValorSaque.setText("Valor R$:");

        cxNumeroContaSaque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaSaqueMouseClicked(evt);
            }
        });
        cxNumeroContaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaSaqueActionPerformed(evt);
            }
        });
        cxNumeroContaSaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaSaqueKeyTyped(evt);
            }
        });

        txNumeroContaSaque.setForeground(new java.awt.Color(255, 255, 255));
        txNumeroContaSaque.setText("Numero da Conta:");

        cxValorSaque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorSaqueFocusLost(evt);
            }
        });
        cxValorSaque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxValorSaqueMouseClicked(evt);
            }
        });
        cxValorSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorSaqueActionPerformed(evt);
            }
        });

        btSacar.setText("Sacar");
        btSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSacarActionPerformed(evt);
            }
        });

        txSenha.setForeground(new java.awt.Color(255, 255, 255));
        txSenha.setText("Senha:");

        pnSaque.setLayer(txTituloSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(pwSenhaSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(txValorSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(cxNumeroContaSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(txNumeroContaSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(cxValorSaque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(btSacar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnSaque.setLayer(txSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnSaqueLayout = new javax.swing.GroupLayout(pnSaque);
        pnSaque.setLayout(pnSaqueLayout);
        pnSaqueLayout.setHorizontalGroup(
            pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSaqueLayout.createSequentialGroup()
                        .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txNumeroContaSaque)
                            .addComponent(txValorSaque)
                            .addComponent(txSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxNumeroContaSaque)
                            .addComponent(cxValorSaque)
                            .addComponent(pwSenhaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSaqueLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txTituloSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnSaqueLayout.setVerticalGroup(
            pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSaqueLayout.createSequentialGroup()
                .addComponent(txTituloSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxNumeroContaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNumeroContaSaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txValorSaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSenha)
                    .addComponent(pwSenhaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSacar))
        );

        pnTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnTransferencia.setOpaque(false);

        txContaDestino.setForeground(new java.awt.Color(255, 255, 255));
        txContaDestino.setText("Numero da Conta Destino:");

        pwSenhaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwSenhaTransferenciaActionPerformed(evt);
            }
        });
        pwSenhaTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwSenhaTransferenciaKeyTyped(evt);
            }
        });

        txTituloTranferencia.setBackground(new java.awt.Color(255, 0, 0));
        txTituloTranferencia.setForeground(new java.awt.Color(255, 255, 255));
        txTituloTranferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txTituloTranferencia.setText("Transferencia");

        txValorTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        txValorTransferencia.setText("Valor R$:");

        cxNumeroContaOrigem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaOrigemMouseClicked(evt);
            }
        });
        cxNumeroContaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaOrigemActionPerformed(evt);
            }
        });
        cxNumeroContaOrigem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaOrigemKeyTyped(evt);
            }
        });

        txContaOrigem.setForeground(new java.awt.Color(255, 255, 255));
        txContaOrigem.setText("Numero da Conta Origem:");

        cxValorTransferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorTransferenciaFocusLost(evt);
            }
        });
        cxValorTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorTransferenciaActionPerformed(evt);
            }
        });

        btTraferir.setText("Tranferir");
        btTraferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTraferirMouseClicked(evt);
            }
        });
        btTraferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraferirActionPerformed(evt);
            }
        });

        txSenhaTranferencia.setForeground(new java.awt.Color(255, 255, 255));
        txSenhaTranferencia.setText("Senha:");

        cxNumeroContaDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaDestinoMouseClicked(evt);
            }
        });
        cxNumeroContaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaDestinoActionPerformed(evt);
            }
        });
        cxNumeroContaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaDestinoKeyTyped(evt);
            }
        });

        pnTransferencia.setLayer(txContaDestino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(pwSenhaTransferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(txTituloTranferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(txValorTransferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(cxNumeroContaOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(txContaOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(cxValorTransferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(btTraferir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(txSenhaTranferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnTransferencia.setLayer(cxNumeroContaDestino, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnTransferenciaLayout = new javax.swing.GroupLayout(pnTransferencia);
        pnTransferencia.setLayout(pnTransferenciaLayout);
        pnTransferenciaLayout.setHorizontalGroup(
            pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTituloTranferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTransferenciaLayout.createSequentialGroup()
                        .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTransferenciaLayout.createSequentialGroup()
                                .addComponent(txContaOrigem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNumeroContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTransferenciaLayout.createSequentialGroup()
                                .addComponent(txContaDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNumeroContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTransferenciaLayout.createSequentialGroup()
                                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txValorTransferencia)
                                    .addComponent(txSenhaTranferencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwSenhaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btTraferir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTransferenciaLayout.setVerticalGroup(
            pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransferenciaLayout.createSequentialGroup()
                .addComponent(txTituloTranferencia)
                .addGap(15, 15, 15)
                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxNumeroContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txContaOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxNumeroContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txContaDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txValorTransferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSenhaTranferencia)
                    .addComponent(pwSenhaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTraferir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDeposito.setBackground(new java.awt.Color(255, 51, 0));
        pnDeposito.setToolTipText("");
        pnDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnDeposito.setOpaque(false);

        txValorDeposito.setForeground(new java.awt.Color(255, 255, 255));
        txValorDeposito.setText("Valor R$:");

        cxNumeroContaDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaDepositoMouseClicked(evt);
            }
        });
        cxNumeroContaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaDepositoActionPerformed(evt);
            }
        });
        cxNumeroContaDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaDepositoKeyTyped(evt);
            }
        });

        txNumeroContaDeposito.setForeground(new java.awt.Color(255, 255, 255));
        txNumeroContaDeposito.setText("Numero da Conta:");

        cxValorDeposito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxValorDepositoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorDepositoFocusLost(evt);
            }
        });
        cxValorDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorDepositoActionPerformed(evt);
            }
        });

        btDepositar.setText("Depositar");
        btDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositarActionPerformed(evt);
            }
        });

        txTituloDeposito.setBackground(new java.awt.Color(255, 0, 0));
        txTituloDeposito.setForeground(new java.awt.Color(255, 255, 255));
        txTituloDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txTituloDeposito.setText("Deposito");

        pnDeposito.setLayer(txValorDeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnDeposito.setLayer(cxNumeroContaDeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnDeposito.setLayer(txNumeroContaDeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnDeposito.setLayer(cxValorDeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnDeposito.setLayer(btDepositar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnDeposito.setLayer(txTituloDeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnDepositoLayout = new javax.swing.GroupLayout(pnDeposito);
        pnDeposito.setLayout(pnDepositoLayout);
        pnDepositoLayout.setHorizontalGroup(
            pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDepositoLayout.createSequentialGroup()
                .addGroup(pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDepositoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txNumeroContaDeposito)
                            .addComponent(txValorDeposito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxNumeroContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDepositoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDepositar))
                    .addComponent(txTituloDeposito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnDepositoLayout.setVerticalGroup(
            pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDepositoLayout.createSequentialGroup()
                .addComponent(txTituloDeposito)
                .addGap(15, 15, 15)
                .addGroup(pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNumeroContaDeposito)
                    .addComponent(cxNumeroContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txValorDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDepositar)
                .addContainerGap())
        );

        pnConsultaRendimento.setBackground(new java.awt.Color(255, 51, 0));
        pnConsultaRendimento.setToolTipText("");
        pnConsultaRendimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnConsultaRendimento.setOpaque(false);

        cxNumeroContaConsultarRendimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxNumeroContaConsultarRendimentoFocusGained(evt);
            }
        });
        cxNumeroContaConsultarRendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaConsultarRendimentoMouseClicked(evt);
            }
        });
        cxNumeroContaConsultarRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaConsultarRendimentoActionPerformed(evt);
            }
        });
        cxNumeroContaConsultarRendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaConsultarRendimentoKeyTyped(evt);
            }
        });

        txNumeroContaRendimento.setForeground(new java.awt.Color(255, 255, 255));
        txNumeroContaRendimento.setText("Numero da Conta:");

        btCalcularRendimento.setText("Calcular Rendimento");
        btCalcularRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularRendimentoActionPerformed(evt);
            }
        });

        txCalculoRendimento.setBackground(new java.awt.Color(255, 0, 0));
        txCalculoRendimento.setForeground(new java.awt.Color(255, 255, 255));
        txCalculoRendimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txCalculoRendimento.setText("Calcular Rendimento Anual");

        pnConsultaRendimento.setLayer(cxNumeroContaConsultarRendimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaRendimento.setLayer(txNumeroContaRendimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaRendimento.setLayer(btCalcularRendimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaRendimento.setLayer(txCalculoRendimento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnConsultaRendimentoLayout = new javax.swing.GroupLayout(pnConsultaRendimento);
        pnConsultaRendimento.setLayout(pnConsultaRendimentoLayout);
        pnConsultaRendimentoLayout.setHorizontalGroup(
            pnConsultaRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultaRendimentoLayout.createSequentialGroup()
                .addGroup(pnConsultaRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConsultaRendimentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txNumeroContaRendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNumeroContaConsultarRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConsultaRendimentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCalcularRendimento))
                    .addComponent(txCalculoRendimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnConsultaRendimentoLayout.setVerticalGroup(
            pnConsultaRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultaRendimentoLayout.createSequentialGroup()
                .addComponent(txCalculoRendimento)
                .addGap(15, 15, 15)
                .addGroup(pnConsultaRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNumeroContaRendimento)
                    .addComponent(cxNumeroContaConsultarRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCalcularRendimento)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        pnConsultaSaldo.setBackground(new java.awt.Color(255, 51, 0));
        pnConsultaSaldo.setToolTipText("");
        pnConsultaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnConsultaSaldo.setOpaque(false);

        cxNumeroContaConsultarSaldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxNumeroContaConsultarSaldoFocusGained(evt);
            }
        });
        cxNumeroContaConsultarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxNumeroContaConsultarSaldoMouseClicked(evt);
            }
        });
        cxNumeroContaConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaConsultarSaldoActionPerformed(evt);
            }
        });
        cxNumeroContaConsultarSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaConsultarSaldoKeyTyped(evt);
            }
        });

        txNumeroContaSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txNumeroContaSaldo.setText("Numero da Conta:");

        btConsultarSaldo.setText("Consultar Saldo");
        btConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoActionPerformed(evt);
            }
        });

        txConsultarSaldo.setBackground(new java.awt.Color(255, 0, 0));
        txConsultarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txConsultarSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txConsultarSaldo.setText("Consultar Saldo");

        pnConsultaSaldo.setLayer(cxNumeroContaConsultarSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaSaldo.setLayer(txNumeroContaSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaSaldo.setLayer(btConsultarSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConsultaSaldo.setLayer(txConsultarSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnConsultaSaldoLayout = new javax.swing.GroupLayout(pnConsultaSaldo);
        pnConsultaSaldo.setLayout(pnConsultaSaldoLayout);
        pnConsultaSaldoLayout.setHorizontalGroup(
            pnConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultaSaldoLayout.createSequentialGroup()
                .addGroup(pnConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnConsultaSaldoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txNumeroContaSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNumeroContaConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConsultaSaldoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultarSaldo))
                    .addComponent(txConsultarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnConsultaSaldoLayout.setVerticalGroup(
            pnConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultaSaldoLayout.createSequentialGroup()
                .addComponent(txConsultarSaldo)
                .addGap(15, 15, 15)
                .addGroup(pnConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNumeroContaSaldo)
                    .addComponent(cxNumeroContaConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultarSaldo)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnSubMetodosLayout = new javax.swing.GroupLayout(pnSubMetodos);
        pnSubMetodos.setLayout(pnSubMetodosLayout);
        pnSubMetodosLayout.setHorizontalGroup(
            pnSubMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSubMetodosLayout.createSequentialGroup()
                .addComponent(Separador)
                .addContainerGap())
            .addGroup(pnSubMetodosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnConsultaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnSubMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnSubMetodosLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pnConsultaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );
        pnSubMetodosLayout.setVerticalGroup(
            pnSubMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSubMetodosLayout.createSequentialGroup()
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnSubMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSubMetodosLayout.createSequentialGroup()
                        .addComponent(pnConsultaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnSubMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSubMetodosLayout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(pnConsultaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnMetodosLayout = new javax.swing.GroupLayout(pnMetodos);
        pnMetodos.setLayout(pnMetodosLayout);
        pnMetodosLayout.setHorizontalGroup(
            pnMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSubMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMetodosLayout.createSequentialGroup()
                .addComponent(pnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnMetodosLayout.setVerticalGroup(
            pnMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMetodosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(pnSubMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txSubTitulo.setText("| CONTAS BANCARIAS |");

        mCriarConta.setText("Criar Contas");

        iCriarContaCorrente.setText("Criar Conta Corrente");
        iCriarContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCriarContaCorrenteActionPerformed(evt);
            }
        });
        mCriarConta.add(iCriarContaCorrente);

        iCriarContaPoupanca.setText("Criar Conta Poupança");
        iCriarContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCriarContaPoupancaActionPerformed(evt);
            }
        });
        mCriarConta.add(iCriarContaPoupanca);

        iCriarContaPoupancaEspeial.setText("Criar Conta Poupança Especial");
        iCriarContaPoupancaEspeial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCriarContaPoupancaEspeialActionPerformed(evt);
            }
        });
        mCriarConta.add(iCriarContaPoupancaEspeial);

        BarraMenu.add(mCriarConta);

        mBuscarConta.setText("Pesquisar Contas");
        mBuscarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mBuscarContaMouseClicked(evt);
            }
        });
        mBuscarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBuscarContaActionPerformed(evt);
            }
        });
        BarraMenu.add(mBuscarConta);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotTituloPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rotTituloPrinc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iCriarContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCriarContaCorrenteActionPerformed
        dispose();
        CriarContaCorrente criarContaCorrente = CriarContaCorrente.getInstance();
        criarContaCorrente.setVisible(true);
    }//GEN-LAST:event_iCriarContaCorrenteActionPerformed

    private void mBuscarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBuscarContaActionPerformed

     }//GEN-LAST:event_mBuscarContaActionPerformed

    private void mBuscarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mBuscarContaMouseClicked
        dispose();

        ConsultaContas consultaContas = ConsultaContas.getInstance();
        consultaContas.limparTabela();
        consultaContas.setVisible(true);

        consultaContas.setVisible(true);    }//GEN-LAST:event_mBuscarContaMouseClicked

    private void iCriarContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCriarContaPoupancaActionPerformed
        dispose();
        CriarContaPoupanca criarContaPoupanca = CriarContaPoupanca.getInstance();
        criarContaPoupanca.setVisible(true);
    }//GEN-LAST:event_iCriarContaPoupancaActionPerformed

    private void iCriarContaPoupancaEspeialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCriarContaPoupancaEspeialActionPerformed
        dispose();
        CriarContaPoupancaEspecial criarContaPoupancaEspecial = CriarContaPoupancaEspecial.getInstance();
        criarContaPoupancaEspecial.setVisible(true);
    }//GEN-LAST:event_iCriarContaPoupancaEspeialActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositarActionPerformed
        depositar();
    }//GEN-LAST:event_btDepositarActionPerformed

    private void cxValorDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorDepositoActionPerformed

    private void cxValorDepositoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorDepositoFocusLost
        formataNumero(cxValorDeposito);
    }//GEN-LAST:event_cxValorDepositoFocusLost

    private void cxNumeroContaDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaDepositoKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaDeposito, evt);
    }//GEN-LAST:event_cxNumeroContaDepositoKeyTyped

    private void cxNumeroContaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaDepositoActionPerformed

    private void cxNumeroContaDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaDepositoMouseClicked
        limparCampo(cxNumeroContaDeposito);
    }//GEN-LAST:event_cxNumeroContaDepositoMouseClicked

    private void cxNumeroContaDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaDestinoKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaDestino, evt);
    }//GEN-LAST:event_cxNumeroContaDestinoKeyTyped

    private void cxNumeroContaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaDestinoActionPerformed

    private void btTraferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTraferirActionPerformed

    private void btTraferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTraferirMouseClicked
        try {
            transferir();
        } catch (InvalidaException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, "Erro não mapeado" + ex.getMessage(), ex);
        }
    }//GEN-LAST:event_btTraferirMouseClicked

    private void cxValorTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorTransferenciaActionPerformed

    private void cxValorTransferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorTransferenciaFocusLost
        formataNumero(cxValorTransferencia);
    }//GEN-LAST:event_cxValorTransferenciaFocusLost

    private void cxNumeroContaOrigemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaOrigemKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaOrigem, evt);
    }//GEN-LAST:event_cxNumeroContaOrigemKeyTyped

    private void cxNumeroContaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaOrigemActionPerformed

    private void pwSenhaTransferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwSenhaTransferenciaKeyTyped
        limitarTamanhoCampo(6, pwSenhaTransferencia, evt);
    }//GEN-LAST:event_pwSenhaTransferenciaKeyTyped

    private void pwSenhaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwSenhaTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwSenhaTransferenciaActionPerformed

    private void btSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSacarActionPerformed
        try {
            sacar();
        } catch (InvalidaException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, "Erro de Exceção Chegou ao Ultimo Nivel" + ex.getMessage(), ex);

        }
    }//GEN-LAST:event_btSacarActionPerformed

    private void cxValorSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorSaqueActionPerformed

    private void cxValorSaqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorSaqueFocusLost
        formataNumero(cxValorSaque);
    }//GEN-LAST:event_cxValorSaqueFocusLost

    private void cxNumeroContaSaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaSaqueKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaSaque, evt);
    }//GEN-LAST:event_cxNumeroContaSaqueKeyTyped

    private void cxNumeroContaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaSaqueActionPerformed

    }//GEN-LAST:event_cxNumeroContaSaqueActionPerformed

    private void cxNumeroContaSaqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaSaqueMouseClicked
        limparCampo(cxNumeroContaSaque);
    }//GEN-LAST:event_cxNumeroContaSaqueMouseClicked

    private void pwSenhaSaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwSenhaSaqueKeyTyped
        limitarTamanhoCampo(6, pwSenhaSaque, evt);
    }//GEN-LAST:event_pwSenhaSaqueKeyTyped

    private void cxValorDepositoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorDepositoFocusGained
        limparCampo(cxValorDeposito);
    }//GEN-LAST:event_cxValorDepositoFocusGained

    private void cxValorSaqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxValorSaqueMouseClicked
        limparCampo(cxValorSaque);
    }//GEN-LAST:event_cxValorSaqueMouseClicked

    private void pwSenhaSaqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwSenhaSaqueMouseClicked
        limparCampo(pwSenhaSaque);
    }//GEN-LAST:event_pwSenhaSaqueMouseClicked

    private void cxNumeroContaOrigemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaOrigemMouseClicked
        limparCampo(cxNumeroContaOrigem);
    }//GEN-LAST:event_cxNumeroContaOrigemMouseClicked

    private void cxNumeroContaDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaDestinoMouseClicked
        limparCampo(cxNumeroContaDestino);
    }//GEN-LAST:event_cxNumeroContaDestinoMouseClicked

    private void btCalcularRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularRendimentoActionPerformed
        calcularRendimentos();
    }//GEN-LAST:event_btCalcularRendimentoActionPerformed

    private void cxNumeroContaConsultarRendimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarRendimentoKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaConsultarRendimento, evt);
    }//GEN-LAST:event_cxNumeroContaConsultarRendimentoKeyTyped

    private void cxNumeroContaConsultarRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarRendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaConsultarRendimentoActionPerformed

    private void cxNumeroContaConsultarRendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarRendimentoMouseClicked
        limparCampo(cxNumeroContaConsultarRendimento);
    }//GEN-LAST:event_cxNumeroContaConsultarRendimentoMouseClicked

    private void cxNumeroContaConsultarRendimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarRendimentoFocusGained

    }//GEN-LAST:event_cxNumeroContaConsultarRendimentoFocusGained

    private void btConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoActionPerformed
        consultarSaldo();
    }//GEN-LAST:event_btConsultarSaldoActionPerformed

    private void cxNumeroContaConsultarSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarSaldoKeyTyped
        limitarTamanhoCampo(6, cxNumeroContaConsultarSaldo, evt);
    }//GEN-LAST:event_cxNumeroContaConsultarSaldoKeyTyped

    private void cxNumeroContaConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaConsultarSaldoActionPerformed

    private void cxNumeroContaConsultarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarSaldoMouseClicked
        limparCampo(cxNumeroContaConsultarSaldo);
    }//GEN-LAST:event_cxNumeroContaConsultarSaldoMouseClicked

    private void cxNumeroContaConsultarSaldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxNumeroContaConsultarSaldoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaConsultarSaldoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        carregaEstilo();

        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton btCalcularRendimento;
    private javax.swing.JButton btConsultarSaldo;
    private javax.swing.JButton btDepositar;
    private javax.swing.JButton btSacar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTraferir;
    private javax.swing.JTextField cxNumeroContaConsultarRendimento;
    private javax.swing.JTextField cxNumeroContaConsultarSaldo;
    private javax.swing.JTextField cxNumeroContaDeposito;
    private javax.swing.JTextField cxNumeroContaDestino;
    private javax.swing.JTextField cxNumeroContaOrigem;
    private javax.swing.JTextField cxNumeroContaSaque;
    private javax.swing.JTextField cxValorDeposito;
    private javax.swing.JTextField cxValorSaque;
    private javax.swing.JTextField cxValorTransferencia;
    private javax.swing.JMenuItem iCriarContaCorrente;
    private javax.swing.JMenuItem iCriarContaPoupanca;
    private javax.swing.JMenuItem iCriarContaPoupancaEspeial;
    private javax.swing.JMenu mBuscarConta;
    private javax.swing.JMenu mCriarConta;
    private javax.swing.JDesktopPane pnConsultaRendimento;
    private javax.swing.JDesktopPane pnConsultaSaldo;
    private javax.swing.JDesktopPane pnDeposito;
    private javax.swing.JPanel pnMetodos;
    private javax.swing.JDesktopPane pnSaque;
    private javax.swing.JPanel pnSubMetodos;
    private javax.swing.JDesktopPane pnTransferencia;
    private javax.swing.JPasswordField pwSenhaSaque;
    private javax.swing.JPasswordField pwSenhaTransferencia;
    private javax.swing.JLabel rotTituloPrinc;
    private javax.swing.JLabel txCalculoRendimento;
    private javax.swing.JLabel txConsultarSaldo;
    private javax.swing.JLabel txContaDestino;
    private javax.swing.JLabel txContaOrigem;
    private javax.swing.JLabel txNumeroContaDeposito;
    private javax.swing.JLabel txNumeroContaRendimento;
    private javax.swing.JLabel txNumeroContaSaldo;
    private javax.swing.JLabel txNumeroContaSaque;
    private javax.swing.JLabel txSenha;
    private javax.swing.JLabel txSenhaTranferencia;
    private javax.swing.JLabel txSubTitulo;
    private javax.swing.JLabel txTituloDeposito;
    private javax.swing.JLabel txTituloSaque;
    private javax.swing.JLabel txTituloTranferencia;
    private javax.swing.JLabel txValorDeposito;
    private javax.swing.JLabel txValorSaque;
    private javax.swing.JLabel txValorTransferencia;
    // End of variables declaration//GEN-END:variables

    private void limitarTamanhoCampo(int tamanhoMaximo, JTextField campo, java.awt.event.KeyEvent evt) {
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
            if (campo.getText().length() == tamanhoMaximo) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            }
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }

    private void formataNumero(JTextField campo) {
        String texto = campo.getText();

        String semLetras = texto.replaceAll("[^\\d.,]", "");

        String resultado = semLetras.replace(",", ".");

        if (!resultado.matches("\\d+\\.\\d{2}")) {

            resultado += ".00";
        }

        campo.setText(resultado);

    }

    private void limparCampo(Component componente) {
        if (componente instanceof JTextField) {
            JTextField textField = (JTextField) componente;
            textField.setText("");
        } else if (componente instanceof JPasswordField) {
            JPasswordField passwordField = (JPasswordField) componente;
            passwordField.setText("");
        }
    }

    private void depositar() {
        String numeroConta = cxNumeroContaDeposito.getText();
        double valorDeposito = Double.parseDouble(cxValorDeposito.getText());

        BancoContas banco = BancoContas.getBanco();
        Conta conta = banco.getContaByNumero(numeroConta);

        if (conta != null) {
            if (conta instanceof ContaPoupanca) {
                double saldoAnterior = conta.getSaldo();
                conta.depositar(valorDeposito);
                double novoSaldo = conta.getSaldo();
                JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso na conta Poupança: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo, "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else if (conta instanceof ContaCorrente) {
                double saldoAnterior = conta.getSaldo();
                conta.depositar(valorDeposito);
                double novoSaldo = conta.getSaldo();
                double limiteDisponivel = ((ContaCorrente) conta).getLimiteDisponivel();
                JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso na conta Corrente: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo + "\nLimite disponível: " + limiteDisponivel, "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else if (conta instanceof ContaPoupancaEspecial) {
                double saldoAnterior = conta.getSaldo();
                conta.depositar(valorDeposito);
                double novoSaldo = conta.getSaldo();
                double limiteDisponivel = ((ContaPoupancaEspecial) conta).getLimiteDisponivel();
                JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso na conta Poupança Especial: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo + "\nLimite disponível: " + limiteDisponivel, "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Conta não encontrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void sacar() throws InvalidaException {
        String numeroConta = cxNumeroContaSaque.getText();
        double valorSaque = Double.parseDouble(cxValorSaque.getText());

        BancoContas banco = BancoContas.getBanco();
        Conta conta = banco.getContaByNumero(numeroConta);

        if (conta != null) {
            String senhaSaque = pwSenhaSaque.getText();
            if (senhaSaque.equals(conta.getSenha())) {
                if (conta instanceof ContaPoupanca) {
                    double saldoAnterior = conta.getSaldo();
                    boolean saqueRealizado = conta.sacar(valorSaque);
                    double novoSaldo = conta.getSaldo();
                    if (saqueRealizado) {
                        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso na conta Poupança: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente na conta Poupança: " + conta.getNumero() + "\nSaldo atual: " + novoSaldo, "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } else if (conta instanceof ContaCorrente) {
                    double saldoAnterior = conta.getSaldo();
                    boolean saqueRealizado = conta.sacar(valorSaque);
                    double novoSaldo = conta.getSaldo();
                    if (saqueRealizado) {
                        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso na conta Corrente: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente na conta Corrente: " + conta.getNumero() + "\nSaldo atual: " + novoSaldo, "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } else if (conta instanceof ContaPoupancaEspecial) {
                    double saldoAnterior = conta.getSaldo();
                    boolean saqueRealizado = conta.sacar(valorSaque);
                    double novoSaldo = conta.getSaldo();
                    if (saqueRealizado) {
                        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso na conta Poupança Especial: " + conta.getNumero() + "\nSaldo anterior: " + saldoAnterior + "\nNovo saldo: " + novoSaldo, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente na conta Poupança Especial: " + conta.getNumero() + "\nSaldo atual: " + novoSaldo, "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Senha incorreta.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Conta não encontrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void transferir() throws InvalidaException {
        String numeroContaOrigem = cxNumeroContaOrigem.getText();
        String numeroContaDestino = cxNumeroContaDestino.getText();
        double valorTransferencia = Double.parseDouble(cxValorTransferencia.getText());

        BancoContas banco = BancoContas.getBanco();
        Conta contaOrigem = banco.getContaByNumero(numeroContaOrigem);
        Conta contaDestino = banco.getContaByNumero(numeroContaDestino);

        if (contaOrigem != null && contaDestino != null) {
            String senhaTransferencia = pwSenhaTransferencia.getText();
            if (senhaTransferencia.equals(contaOrigem.getSenha())) {
                if (contaOrigem instanceof ContaCorrente) {
                    double saldoAnteriorOrigem = contaOrigem.getSaldo();
                    double saldoAnteriorDestino = contaDestino.getSaldo();

                    ContaCorrente contaCorrenteOrigem = (ContaCorrente) contaOrigem;

                    boolean transferenciaRealizada = contaCorrenteOrigem.transferir(contaDestino, valorTransferencia);

                    double novoSaldoOrigem = contaCorrenteOrigem.getSaldo();
                    double novoSaldoDestino = contaDestino.getSaldo();

                    if (transferenciaRealizada) {
                        double limiteDisponivelOrigem = contaCorrenteOrigem.getLimiteDisponivel();

                        JOptionPane.showMessageDialog(this, """
                                                Transfer\u00eancia realizada com sucesso:
                                                Conta de origem: """ + contaOrigem.getNumero() + "\n"
                                + "Saldo anterior: " + saldoAnteriorOrigem + "\n"
                                + "Novo saldo: " + novoSaldoOrigem + "\n"
                                + "Limite disponível: " + limiteDisponivelOrigem + "\n\n"
                                + "Conta de destino: " + contaDestino.getNumero() + "\n"
                                + "Saldo anterior: " + saldoAnteriorDestino + "\n"
                                + "Novo saldo: " + novoSaldoDestino, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente na conta de origem: " + contaOrigem.getNumero() + "\nSaldo atual: " + novoSaldoOrigem, "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Apenas contas correntes podem realizar transferências.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Senha incorreta para a conta de origem.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Conta de origem ou conta de destino não encontrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void consultarSaldo() {
        String numeroContaConsultarSaldo = cxNumeroContaConsultarSaldo.getText();
        BancoContas banco = BancoContas.getBanco();
        Conta contaConsultarSaldo = banco.getContaByNumero(numeroContaConsultarSaldo);

        if (contaConsultarSaldo != null) {
            double saldoConta = contaConsultarSaldo.getSaldo();
            String tipoConta = "";
            double saldoLimite = 0.0;
            double saldoTotal = 0.0;

            if (contaConsultarSaldo instanceof ContaPoupanca) {
                tipoConta = "Poupança";
                saldoTotal = saldoConta + saldoLimite;
            } else if (contaConsultarSaldo instanceof ContaCorrente) {
                tipoConta = "Corrente";
                saldoLimite = ((ContaCorrente) contaConsultarSaldo).getLimite();
                saldoTotal = saldoConta + saldoLimite;
            } else if (contaConsultarSaldo instanceof ContaPoupancaEspecial) {
                tipoConta = "Poupança Especial";
                saldoLimite = ((ContaPoupancaEspecial) contaConsultarSaldo).getLimiteDisponivel();
                saldoTotal = saldoConta + saldoLimite;
            }

            JOptionPane.showMessageDialog(this, "Saldo da conta " + numeroContaConsultarSaldo + " (" + tipoConta + ")\nSaldo em Conta: R$ " + saldoConta
                    + "\nSaldo no Limite: R$ " + saldoLimite
                    + "\nSaldo Total: R$ " + saldoTotal, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Conta não encontrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void calcularRendimentos() {
        String numeroConta = cxNumeroContaConsultarRendimento.getText();
        BancoContas banco = BancoContas.getBanco();
        Conta conta = banco.getContaByNumero(numeroConta);

        if (conta != null) {
            double rendimentos = 0.0;

            if (conta instanceof ContaPoupanca) {
                ContaPoupanca contaPoupanca = (ContaPoupanca) conta;
                rendimentos = contaPoupanca.calcularRendimento();
            } else if (conta instanceof ContaPoupancaEspecial) {
                ContaPoupancaEspecial contaPoupancaEspecial = (ContaPoupancaEspecial) conta;
                rendimentos = contaPoupancaEspecial.calcularRendimento();
            } else {
                JOptionPane.showMessageDialog(this, "Não é possível calcular rendimentos para essa conta.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Rendimentos da conta " + numeroConta + ": R$ " + rendimentos, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Conta não encontrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private static void carregaEstilo() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

}
